name: Performance - Lighthouse

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  # Allows workflow to be called from other workflows
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      externalCall:
        description: "To distinguish workflow_call from regular push"
        type: boolean
        required: false
        default: false

# Avoid duplicate workflows on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-performance-lighthouse
  cancel-in-progress: true

jobs:
  performance-lighthouse:
    # Only run this job if the PR has the label 'perf:lighthouse' or if it's been called by another workflow
    # See https://github.com/actions/runner/discussions/1884 for discussion on why `externalCall` is used
    if: contains(github.event.pull_request.labels.*.name, 'perf:lighthouse') || inputs.externalCall
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Set Python version vars
        uses: ./.github/actions/build_info
      - name: Set up Python ${{ env.PYTHON_MAX_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_MAX_VERSION }}"
      - name: Setup virtual env
        uses: ./.github/actions/make_init
      - name: Run make frontend-fast
        run: make frontend-fast
      - name: Run Performance Lighthouse
        run: make performance-lighthouse
      - name: Set MY_DATE_TIME env var
        run: echo "MY_DATE_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: performance_lighthouse_${{ env.MY_DATE_TIME }}
          path: frontend/app/performance/lighthouse/reports
